# Generated by Django 4.2.23 on 2025-07-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_keshav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keshav',
        ),
    ]
