# Generated by Django 4.2.23 on 2025-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(choices=[('Study', 'Study'), ('Exercise', 'Exercise'), ('Reading', 'Reading'), ('Work', 'Work')], max_length=50, unique=True),
        ),
    ]
