# Generated by Django 4.2.23 on 2025-07-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_alter_taskcategory_options_alter_taskcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('progress', models.CharField(choices=[('completed', 'Completed'), ('halfway', 'Halfway'), ('started', 'Started'), ('pending', 'Pending')], max_length=10)),
                ('points', models.FloatField(default=0.0)),
                ('consistency_bonus', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'date')},
            },
        ),
    ]
