# Generated by Django 4.2.23 on 2025-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_userprofile_notification_dailysummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='progress',
            field=models.CharField(choices=[(2, 'Completed'), (1, 'Halfway'), (1, 'Started'), (1, 'Pending')], max_length=10),
        ),
    ]
